services:
#- type: web
#  name: line-bot-ruby-echo
#  env: ruby
#  repo: https://github.com/terry255180/line-bot-sdk-ruby.git
#  buildCommand: cd examples/echobot;BUNDLE_DEPLOYMENT=false bundle install
#  startCommand: cd examples/echobot;bundle exec ruby app.rb
#  plan: free
#  autoDeploy: false
#  envVars:
#  - key: LINE_CHANNEL_TOKEN
#    sync: false
#  - key: LINE_CHANNEL_SECRET
#    sync: false
- type: web
  name: line-bot-ruby-kitchensink
  env: ruby
  repo: https://github.com/terry255180/line-bot-sdk-ruby.git
  buildCommand: cd examples/kitchensink;gem install sinatra line-bot-api
  startCommand: cd examples/kitchensink;ruby app.rb
  plan: free
  autoDeploy: false
  envVars:
  - key: El6tU2eGU1tEvjEWxsW6kFidUprY89ZbWPn5HpDjYLxx0szdGHIP6l/FEiQGDxpKavPQgLrLNaIgyO5BQX4e4bAVvI8IP7OpSPX/XzCkLbSqVrVj/Y3eEsv2odmqE22f22zEVh3TLUfuPRyZawxAowdB04t89/1O/w1cDnyilFU=
    sync: false
  - key: dc62e62d81121757e6b1c2b35d347599
    sync: false
